language: c
before_script:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
- "./travis-tool.sh install_deps"
- ./travis-tool.sh github_package jimhester/covr


script: 
- "./travis-tool.sh run_tests"


env:
  global:
  - R_BUILD_ARGS=" "
  - R_CHECK_ARGS="--as-cran"
  - BOOTSTRAP_LATEX="1"

after_failure:
- "./travis-tool.sh dump_logs"
- Rscript -e 'library(covr);coveralls()'

after_success:
- Rscript -e 'library(covr);coveralls()'