language: r

after_failure:
- "./travis-tool.sh dump_logs"
- Rscript -e 'library(covr);coveralls()'

before_script:
  - Rscript -e "install.packages('knitr',repos='http://cran.cnr.Berkeley.edu/')"
  - Rscript -e "install.packages('rmarkdown',repos='http://cran.cnr.Berkeley.edu/')"


after_success:
- Rscript -e 'library(covr);coveralls()'