language: r

after_failure:
- "./travis-tool.sh dump_logs"
- Rscript -e 'library(covr);coveralls()'

before_script:
  - Rscript -e "install.packages('knitr')"
  - Rscript -e "install.packages('rmarkdown')"


after_success:
- Rscript -e 'library(covr);coveralls()'